services:
  - type: web
    name: mathmaster
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /assets/*
        destination: /assets/*
      - type: rewrite
        source: /*
        destination: /index.html
